### ISSUE TITLE
Multi-Session Authentication Bug: Local Logout Invalidates All Sessions

### ISSUE THREAD

**Issue by omkargade04** [supabase/auth#2036]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When multiple sessions are enabled (`SESSIONS_SINGLE_PER_USER = false`), logging out from one device incorrectly invalidates sessions on all other devices, even when using `scope: 'local'`. This breaks the expected behavior of independent multi-device sessions where local logout should only affect the current session.

## To Reproduce

1. Configure GoTrue with `SESSIONS_SINGLE_PER_USER = false` to enable multiple sessions
2. Login on Device A using `supabase.auth.signInWithPassword()`
3. Login on Device B using the same credentials with `supabase.auth.signInWithPassword()`
4. Verify both devices have active sessions by calling `supabase.auth.getSession()` on both
5. On Device A, call `supabase.auth.signOut({ scope: 'local' })`
6. On Device B, call `supabase.auth.getSession()`
7. See error: Device B session is invalidated and returns "session not found"

## Expected behavior

- `signOut({ scope: 'local' })` should only revoke the current session on Device A
- `getSession()` on Device B should continue working with valid refresh tokens
- Multiple active sessions should remain completely independent
- Each device should maintain its own isolated session and refresh token family

## Screenshots

N/A - This is a backend authentication logic issue

## System information

- OS: macOS, Linux (server-side issue affects all platforms)
- Browser: All browsers (affects backend GoTrue authentication)
- Version of supabase-js: Latest (issue is in GoTrue backend, not client library)
- Version of Node.js: N/A (GoTrue is written in Go)
- GoTrue Version: Current main branch

## Additional context

**Root Cause Analysis:**
- Multiple devices receive identical session tokens instead of unique ones
- All devices share the same refresh token family, causing cross-device token invalidation
- Local logout operations affect shared session resources instead of being isolated
- Session cleanup logic doesn't properly respect scope boundaries

**Impact:**
- High severity - breaks core multi-session functionality
- Users are unexpectedly logged out from other devices
- Contradicts documented GoTrue behavior for multiple sessions

**Configuration:**
```
SESSIONS_SINGLE_PER_USER = false
REFRESH_TOKEN_ROTATION_ENABLED = true
```

**Affected Components:**
- Session token generation and validation
- Refresh token family management
- Logout scope implementation
- Multi-session isolation logic

This issue prevents reliable use of multi-device authentication and affects any application relying on independent sessions across multiple devices.

**Comment by j4w8n** [comment]
I don't experience the logout issue you're describing when I switch to "local" `signOut`s. I'm testing on the same device, but different browsers. You may need to provide a minimal code repro of it.

I'm solely using supabase-js, and my demo app was on version 2.49.4. I updated it to the latest (2.49.8) and it's still working as expected. I'm using server-side logouts, but that shouldn't matter.
```js
await supabase.auth.signOut({ scope: 'local' })
```

**Comment by omkargade04** [comment]
@j4w8n, you're absolutely right, and this is actually great news! 🎉

The fact that you can't reproduce the issue when using `scope: 'local'` confirms that the fix should work fine 

**The core problem was:** JavaScript client defaulted to `scope: 'global'`, so when developers called `signOut()` without parameters, it would terminate ALL sessions across devices.

**Our fix:** We changed the default to `scope: 'local'` in our implementation, which prevents the accidental global logout.

Your testing validates that:
1. ✅ `scope: 'local'` works correctly (sessions remain independent)
2. ✅ The multi-session bug was primarily caused by the default scope issue
3. ✅ Our fix addresses the main cause of the problem

Could you please take a look at this PR - https://github.com/supabase/supabase/pull/35960
See if it makes sense

Thank you for testing this - it's exactly the validation we needed to confirm the fix is effective!

**Comment by omkargade04** [comment]
Thank you for testing this! Your feedback is really valuable. A few questions to help narrow this down:

1. **Testing Environment**: You mentioned testing on the same device with different browsers. The original bug reports typically involve **different physical devices** (e.g., phone + laptop, or two different computers). Could you test with actual separate devices if possible?

2. **Session Storage**: Different browsers on the same device use separate localStorage, which might behave differently than sessions across physical devices that could potentially share session tokens.

3. **Server-Side Logout**: You mentioned using server-side logout - are you calling the logout endpoint directly on your backend, or using `supabase.auth.signOut()` from the client?

4. **Configuration**: What's your `SESSIONS_SINGLE_PER_USER` setting? (This requires Pro plan to configure)

The fact that you can't reproduce it with `scope: 'local'` is encouraging - it suggests the fix might be working in many cases. The bug might be:
- Specific to cross-device scenarios (not cross-browser)
- Related to certain configuration combinations
- Already partially fixed in recent versions

Could you try reproducing with:
- Two different physical devices/computers
- Both using client-side `await supabase.auth.signOut({ scope: 'local' })`
- Same user account logged in on both

If you still can't reproduce it, that would be great news - it might mean the issue is resolved or much more limited in scope than initially thought.

**Comment by omkargade04** [comment]
Exactly!  

Since you confirmed that:
- `scope: 'local'` keeps sessions independent 
- Default `signOut()` terminates all sessions (as designed)

Our fix of **changing the JavaScript client default from `'global'` to `'local'`** should solve the multi-session issue while maintaining backward compatibility for those who explicitly want global logout.

This would make JavaScript consistent with Dart/Kotlin clients and prevent accidental global logouts.

Am I right here?

**Comment by j4w8n** [comment]
> Exactly!  
> 
> Since you confirmed that:
> - `scope: 'local'` keeps sessions independent 
> - Default `signOut()` terminates all sessions (as designed)
> 
> Our fix of **changing the JavaScript client default from `'global'` to `'local'`** should solve the multi-session issue while maintaining backward compatibility for those who explicitly want global logout.
> 
> This would make JavaScript consistent with Dart/Kotlin clients and prevent accidental global logouts.
> 
> Am I right here?

It would; but it remains to be seen if the team wants to introduce that breaking change.

I didn't realize the other clients had a different default - I'm just living in the javascript world here.

**Comment by omkargade04** [comment]
@j4w8n Quick question about your explanation:

If global scope `signOut()` revokes refresh tokens on ALL devices (causing them to eventually fail when they try to refresh), isn't this exactly the multi-session bug users are experiencing?

When someone logs out on their phone, they probably expect to stay logged in on their laptop - but the current default global behavior breaks that expectation.

Do you think changing the JavaScript default to `scope: 'local'` (to match Dart/Kotlin) would solve this issue?

**Comment by Preetam7064** [comment]
> > When someone logs out on their phone, they probably expect to stay logged in on their laptop - but the current default global behavior breaks that expectation.
> > Do you think changing the JavaScript default to scope: 'local' (to match Dart/Kotlin) would solve this issue?
> 
> I can understand that user expectation. Defining `scope: 'local'` in your `signOut` code is supposed to solve it.

Hi @j4w8n , thanks for the explanation. I understand that setting scope: 'local' should ideally preserve the session on other devices, and that’s the expected behavior.

However, in my case, even after using scope: 'local' when calling signOut() in my React web app, I’m still encountering a 403 Forbidden error when calling getUser() (https://supabase.com/docs/reference/javascript/auth-getuser)in my React Native apps. It seems like the session is being invalidated globally despite the local scope being specified.

Is this the intended behavior, or could there be something else interfering with the session across platforms?

**Comment by Preetam7064** [comment]
I am getting "no session found" or session is invalidated for other logged in accounts.

**Comment by j4w8n** [comment]
> I am getting "no session found" or session is invalidated for other logged in accounts.

On what devices, when making what calls? Can you paste the actual error?

**Comment by patilrush9** [comment]
We are encountering an unexpected behavior with user sessions when using Supabase Authentication, specifically related to multi-device logins and session invalidation.

Observed Scenario:

A user logs into our application via an Android app.
The same user also logs into the application via our website.
The user then logs out only from the website.
Unexpected Behavior:

After logging out from the website, the active session for the Android app (which was not logged out) becomes invalid. Subsequent API calls from the Android app that require an authenticated session (e.g., get user details from session api) fail with the following error:

{
    "code": 403,
    "error_code": "session_not_found",
    "msg": "Session from session_id claim in JWT does not exist"
}
This occurs even when we explicitly use supabase.auth.signOut({ scope: "local" }) on the website, which we understood should only expire or remove the token from that specific local session (the website).

Analysis
Through our analysis of the authentication flow, we've identified two primary issues:

Shared Session/Token Across Multiple Devices: When a user logs in from multiple devices (e.g., Android app and website), it appears they are using the same underlying session and token across all devices. This is contrary to expected multi-session management where each login should ideally yield a distinct, independent session.
Global Session Invalidation on Local Logout: The supabase.auth.signOut({ scope: "local" }) function is not behaving as expected. Instead of only affecting the local website session, it seems to be invalidating the global session, thereby making the token used by the active Android app session invalid, even though the user did not explicitly log out from the app.
Impact
This issue is critical as our Python backend applications also rely on these tokens for user authentication. When a user's session is unexpectedly invalidated from the website, any active requests from their Android app (from which they did not log out) also fail, leading to a broken user experience and 403 errors in our backend logs for what should be valid requests.

We are seeking guidance or a solution to ensure that:

Each login creates an independent session/token.
supabase.auth.signOut({ scope: "local" }) indeed performs a local logout without affecting other active sessions.

**Comment by tanmays** [comment]
> I didn't realize the other clients had a different default - I'm just living in the javascript world here.

Even the Swift SDK defaults to `global` scope and used to cause session invalidation issues for me. Switching to `local`, did indeed solve the issue and sessions on different devices remain valid. To be sure I tested this again on two separate iOS simulators and it worked as intended.

I took a look at the Kotlin implementation and it indeed defaults to `local`. This behavior needs to be standard across all platforms, there's no reason it should default to global in any platform.

**Comment by Preetam7064** [comment]
@j4w8n yes it is creating multiple sessions for multiple login but when we signout with scope local it is removing all the sessions from that table. Is it issue with supabase-js version code 2.20.0. Code->supabase.auth.signOut({ scope: "local" })

**Comment by Preetam7064** [comment]
@j4w8n the scope is working now as i have upgraded supabase-js from 2.20.0 to 2.49.8. Thanks!

**Comment by Preetam7064** [comment]
@j4w8n a point to be noted, the same version(2.20.0) is working for my react native apps but the scope is not working in my react web apps.

**Comment by j4w8n** [comment]
@Preetam7064 not sure about it working in react native apps. I will say that the feature was technically introduced in auth-js v.2.39.0, so if you were doing a package version override or something in that project, it could've been working even though you only had supabase-js v2.20.0.

**Comment by Preetam7064** [comment]
@j4w8n no problem, we are happy that it got resolved.
